CREATE TABLE `figura`.`user` (`userId` INT(11) NOT NULL AUTO_INCREMENT , `email` VARCHAR(255) NOT NULL , `pwd` VARCHAR(255) NOT NULL , `firstName` VARCHAR(255) NOT NULL , `secondName` VARCHAR(255) NOT NULL , `admin` BOOLEAN NOT NULL , PRIMARY KEY (`userId`)) ENGINE = InnoDB;
CREATE TABLE `figura`.`menuitems` (`itemId` INT(11) NOT NULL AUTO_INCREMENT , `itemName` VARCHAR(255) NOT NULL , `itemPrice` INT(255) NOT NULL , `categoryId` INT(11) NOT NULL , `itemDescription` VARCHAR(255) NOT NULL , PRIMARY KEY (`itemId`)) ENGINE = InnoDB;
CREATE TABLE `figura`.`category` (`id` INT(2) NOT NULL , `name` INT NOT NULL ) ENGINE = InnoDB;
CREATE TABLE `figura`.`ordercon` (`userId` INT(11) NOT NULL , `itemId` INT(11) NOT NULL , `status` INT(1) NOT NULL ) ENGINE = InnoDB;
CREATE TABLE `figura`.`address` (`userId` INT(11) NOT NULL , `city` VARCHAR(255) NOT NULL , `postalCode` INT(4) NOT NULL , `door` VARCHAR(255) NULL , PRIMARY KEY (`userId`)) ENGINE = InnoDB;
INSERT INTO `category`(`name`) VALUES ('Levesek');INSERT INTO `category`(`name`) VALUES ('Előételek');INSERT INTO `category`(`name`) VALUES ('Húsételek');INSERT INTO `category`(`name`) VALUES ('Hal ételek');INSERT INTO `category`(`name`) VALUES ('Tészták');INSERT INTO `category`(`name`) VALUES ('Köretek');INSERT INTO `category`(`name`) VALUES ('Kímélő ételek');INSERT INTO `category`(`name`) VALUES ('Gyermek menük');INSERT INTO `category`(`name`) VALUES ('Saláták');INSERT INTO `category`(`name`) VALUES ('Pizzák');INSERT INTO `category`(`name`) VALUES ('Tejfölös alapú pizzák');INSERT INTO `category`(`name`) VALUES ('Specialitások');INSERT INTO `category`(`name`) VALUES ('Desszertek');
ALTER TABLE `address` CHANGE `userId` `userId` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `address` ADD `Address` VARCHAR(255) NOT NULL AFTER `door`;
ALTER TABLE `address` ADD `phone` varchar(255) NOT NULL AFTER `Address`;
ALTER TABLE `ordercon` ADD `orderId` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`orderId`);
CREATE TABLE `figura`.`orderstatus` (`statusId` INT(11) NOT NULL , `statusName` INT NOT NULL , PRIMARY KEY (`statusId`)) ENGINE = InnoDB;
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Fokhagyma krémleves',795,1);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Paradicsomleves mozzarellával',975,1);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Húsleves gazdagon házi májgombóccal',1210,1);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Magyaros gulyásleves',1340,1);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Camambert rántva áfonyalekvárral',2185,2);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Rántott Trappista sajt majonézzel',2185,2);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Klasszikus sertéspörkölt',2185,3);
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Fokhagymás-tejfölös rántott szelet sajttal',2185,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Rántott sertésszelet (GM)',2185,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Rántott sertésszelet extra adag (GM)',2915,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Cordon Bleu sertéskarajból',2185,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Szaftos cigánypecsenye',2185,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Parmezános bundás csirkemell chilis avokádós majonézzel',2305,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`, `itemDescription`) VALUES ('Hawaii csirkemell',2305,3,'sajt, sonka, ananász');INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Kapros juhtúróval töltött csirkemell szezámmagos bundában',2305,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Vadsült áfonyalekvárral',3040,3);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Pisztráng egészben, mandulás bundában',135,4,'Ft/dkg');INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Egész fogas, roston sütve',185,4,'Ft/dkg');
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Túrós csusza szalonnapörccel',1940,5);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Spagetti bolognai módra',1940,5);
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Steakburgonya',915,6);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Krokett',670,6);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Hasábburgonya',670,6);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Galuska',670,6);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Párolt rizs',670,6);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Pirított burgonya',670,6);
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Rántott gombafej tartármártással',1695,7);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Görög pásztorsaláta',1695,7,"jégsaláta, sárgarépa, lilakáposzta, fetasajt, fokhagyma, olívia");INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Fitness saláta',2305,7,"jégsaláta, csirkemell csíkok, sárgarpéa, cékla, kukorica");INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Dínó falatkák hasábburgonyával',1085,8);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Nutellás palacsinta',670,8);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Csemegeuborka',610,9);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Káposztasaláta',610,9);INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`) VALUES ('Házi vegyes vágott',610,9);
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Margarit',1290,10,"Par., sajt, paradicsomkarika, bazsalikom");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Pumukli',1490,10,"Par., sajt, sonka");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Vegas',1550,10,"Par., sajt, kukorica, brokkoli, gomba, olíva");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Stan',1550,10,"Par., sajt, sonka, gomba");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Kukori',1550,10,"Par., sajt, sonka, kukorica");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Pan',1550,10,"Par., sajt, szalámi");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Marly',1550,10,"Par., sajt, sonka, ananász");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Vivaldi',1750,10,"Par., négy féle sajt");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Hemingway',1750,10,"Par., sajt, tonhal, hagyma, olivabogyó");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Csikós',1550,10,"Par., sajt, kolbász, hagyma, paprika");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Betyár',1550,10,"Par., sajt, sonka, hagyma, bacon");
INSERT INTO `menuitems`(`itemName`, `itemPrice`, `categoryId`,`itemDescription`) VALUES ('Top Gun',1750,10,"Par., sajt, sonka, szalámi, gomba, kukorica");
INSERT INTO `orderstatus`(`statusId`, `statusName`) VALUES ('1','Rendelés feldolgozás alatt');
INSERT INTO `orderstatus`(`statusId`, `statusName`) VALUES ('2','A rendelés készül');
INSERT INTO `orderstatus`(`statusId`, `statusName`) VALUES ('3','A rendelést átadtuk a futárnak');

INSERT INTO `orderstatus`(`statusId`, `statusName`) VALUES ('0','Kosárban')


ALTER TABLE `address` ADD FOREIGN KEY (`userId`) REFERENCES `user`(`userId`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `menuitems` ADD FOREIGN KEY (`categoryId`) REFERENCES `category`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `ordercon` ADD FOREIGN KEY (`status`) REFERENCES `orderstatus`(`statusId`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `ordercon` ADD FOREIGN KEY (`userId`) REFERENCES `user`(`userId`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `ordercon` ADD FOREIGN KEY (`itemId`) REFERENCES `menuitems`(`itemId`) ON DELETE RESTRICT ON UPDATE RESTRICT;
RENAME TABLE `figura`.`user` TO `figura`.`users`;